# src/five_elements.py

"""
This module centralizes the core cosmological data for the game,
including the relationships between the Five Elements, Celestial Stems,
and Terrestrial Branches, as per the game rules.
"""

# --- Five Elements Core Data ---

ELEMENTS = ["wood", "fire", "earth", "metal", "water"]

# The Generating Cycle (相生)
GENERATING_CYCLE = {
    "wood": "fire",
    "fire": "earth",
    "earth": "metal",
    "metal": "water",
    "water": "wood",
}

# The Overcoming Cycle (相克)
OVERCOMING_CYCLE = {
    "wood": "earth",
    "earth": "water",
    "water": "fire",
    "fire": "metal",
    "metal": "wood",
}

# --- Celestial Stems (天干) ---

CELESTIAL_STEMS = {
    # Yang
    "jia": {"element": "wood", "yin_yang": "yang"},
    "bing": {"element": "fire", "yin_yang": "yang"},
    "wu": {"element": "earth", "yin_yang": "yang"},
    "geng": {"element": "metal", "yin_yang": "yang"},
    "ren": {"element": "water", "yin_yang": "yang"},
    # Yin
    "yi": {"element": "wood", "yin_yang": "yin"},
    "ding": {"element": "fire", "yin_yang": "yin"},
    "ji": {"element": "earth", "yin_yang": "yin"},
    "xin": {"element": "metal", "yin_yang": "yin"},
    "gui": {"element": "water", "yin_yang": "yin"},
}

# --- Terrestrial Branches (地支) ---

TERRESTRIAL_BRANCHES = {
    "zi": {"element": "water"},  # Rat
    "chou": {"element": "earth"}, # Ox
    "yin": {"element": "wood"},   # Tiger
    "mao": {"element": "wood"},   # Rabbit
    "chen": {"element": "earth"}, # Dragon
    "si": {"element": "fire"},    # Snake
    "wu": {"element": "fire"},    # Horse
    "wei": {"element": "earth"}, # Goat
    "shen": {"element": "metal"}, # Monkey
    "you": {"element": "metal"}, # Rooster
    "xu": {"element": "earth"},  # Dog
    "hai": {"element": "water"},  # Pig
}

def get_element_for_stem(stem_id: str) -> str | None:
    """Returns the Five Element for a given Celestial Stem ID."""
    return CELESTIAL_STEMS.get(stem_id, {}).get("element")

def get_element_for_branch(branch_id: str) -> str | None:
    """Returns the Five Element for a given Terrestrial Branch ID."""
    return TERRESTRIAL_BRANCHES.get(branch_id, {}).get("element")

def get_generated_element(element: str) -> str | None:
    """Returns the element that is generated by the input element."""
    return GENERATING_CYCLE.get(element)

def get_overcome_element(element: str) -> str | None:
    """Returns the element that is overcome by the input element."""
    return OVERCOMING_CYCLE.get(element)